---

- name: Build webpage locally
  hosts: localhost
  connection: local
  tasks:
    - name: Build blog webpage with HUGO
      shell: "hugo"
      register: "output"
    - debug: var=output.stdout_lines

- name: Deploy blog to webservers
  hosts: webservers
  tasks:
    - name: Create webpage directory
      file:
        state: directory
        path: /data/web/e63197/html/blog.thym.at
        owner: e63197
        group: e63197
        mode: 0755
    - name: Copy blog public dir to remote host
      copy:
        src: public/
        dest: /data/web/e63197/html/blog.thym.at
        owner: e63197
        group: e63197
        mode: 0755
